const setLabel = [
    {
        datetime: "0:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "1:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "2:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "3:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "4:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "5:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "6:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "7:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "8:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "9:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "10:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "11:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "12:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "13:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "14:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "15:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "16:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "17:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "18:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "19:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "20:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "21:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "22:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "23:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "0:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "1:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "2:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "3:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "4:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "5:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "6:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "7:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "8:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "9:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "10:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "11:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "12:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "13:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "14:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "15:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "16:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "17:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "18:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "19:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "20:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "21:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "22:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
    {
        datetime: "23:00",
        value_actual: 0,
        value_rain: 0,
        value_temp: 0,
    },
];

export {setLabel};